server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ms-rutaexpress-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
